### ISSUE TITLE
Is Guava 18 required? 

### ISSUE THREAD

**Issue by unitydynamics** [spotify/async-datastore-client#21]
I seem to be getting errors when running with Guava 21.

java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.transform(...

*update* to answer my own question yes it seems this works specifically with Guava 18.  Not a big deal for me but might consider moving it forward if you can.  Thank you for making this library... I will report errors if I run into them.  It's crazy that Google doesn't have an answer for asynchronous datastore writing.

**Comment by alanw** [comment]
Thanks for the heads-up Robert. 

I've bumped the Guava dependency and fixed the incompatibilities.
